[2025-04-18T19:23:48.863+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.download_raw_data manual__2025-04-18T19:23:37.431616+00:00 [queued]>
[2025-04-18T19:23:48.924+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.download_raw_data manual__2025-04-18T19:23:37.431616+00:00 [queued]>
[2025-04-18T19:23:48.925+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-04-18T19:23:48.966+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): download_raw_data> on 2025-04-18 19:23:37.431616+00:00
[2025-04-18T19:23:48.983+0000] {standard_task_runner.py:57} INFO - Started process 182 to run task
[2025-04-18T19:23:49.037+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'download_raw_data', 'manual__2025-04-18T19:23:37.431616+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmp660h4a83']
[2025-04-18T19:23:49.066+0000] {standard_task_runner.py:85} INFO - Job 65: Subtask download_raw_data
[2025-04-18T19:23:49.164+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-18T19:23:49.457+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.download_raw_data manual__2025-04-18T19:23:37.431616+00:00 [running]> on host e929439072d8
[2025-04-18T19:23:49.890+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='download_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T19:23:37.431616+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T19:23:37.431616+00:00'
[2025-04-18T19:23:49.894+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-18T19:23:49.990+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/opt/***/scripts/download_data.sh ']
[2025-04-18T19:23:50.374+0000] {subprocess.py:86} INFO - Output:
[2025-04-18T19:23:50.416+0000] {subprocess.py:93} INFO - [2025-04-18 19:23:50] INFO: Script started, processing fashion retail stores dataset
[2025-04-18T19:23:50.479+0000] {subprocess.py:93} INFO - [2025-04-18 19:23:50] INFO: Downloading dataset from Kaggle...
[2025-04-18T19:26:28.200+0000] {subprocess.py:93} INFO - [2025-04-18 19:26:28] INFO: Extracting files to /opt/***/data/raw...
[2025-04-18T19:28:27.635+0000] {subprocess.py:93} INFO - [2025-04-18 19:28:27] INFO: Cleaning temporary files...
[2025-04-18T19:28:28.712+0000] {subprocess.py:93} INFO - [2025-04-18 19:28:28] INFO: Processing completed! Data files available at: /opt/***/data/raw
[2025-04-18T19:28:28.714+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-18T19:28:28.819+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=download_raw_data, execution_date=20250418T192337, start_date=20250418T192348, end_date=20250418T192828
[2025-04-18T19:28:29.201+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-18T19:28:29.699+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
